# Generated by Django 4.2.1 on 2023-05-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ST', 'Entradas'), ('MD', 'Platos principales'), ('DR', 'Bebidas'), ('DE', 'Postres'), ('IC', 'Helados')], max_length=2)),
                ('available', models.BooleanField()),
            ],
        ),
    ]
